version: '2'
services:
  ucd-server:
    image: ibmcom/ucds
    ports:
      - 8443:8443
      - 7918:7918
  ucd-relay:
    image: ibmcom/ucdr
    ports:
      - 7916:7916
      - 20080:20080
      - 20081:20081
    depends_on:
      - ucd-server
  ucd-agent-a:
    image: ibmcom/ucda
    environment:
    - AGENT_NAME=ucd-agent-a
    depends_on:
      - ucd-server
      - ucd-relay
  ucd-agent-b:
    image: ibmcom/ucda
    environment:
    - AGENT_NAME=ucd-agent-b
    depends_on:
      - ucd-server
      - ucd-relay