version: '3.7'

services:
  jenkins-dind:
    build:
      context: ../docker-images/jenkins
      # target: jenkins-dind
    restart: "unless-stopped"
    privileged: true
    # user: root
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false -Djava.awt.headless=true"
      - DOCKER_GID_ON_HOST=20 # MAc $(id -g) Linux $(cat /etc/group | grep docker: | cut -d: -f3)
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: "--plugins=blueocean:1.19.0"

volumes:
  jenkins-home:
    name: jenkins-home